/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EaButton: typeof import('@rookie-ui/element-plus')['Button']
    EaChooseCity: typeof import('@rookie-ui/element-plus')['ChooseCity']
    EaChooseTime: typeof import('@rookie-ui/element-plus')['ChooseTime']
    EaChooseDate: typeof import('@rookie-ui/element-plus')['ChooseDate']
    EaChooseIcon: typeof import('@rookie-ui/element-plus')['ChooseIcon']
    EaChooseArea: typeof import('@rookie-ui/element-plus')['ChooseArea']
    EaTable: typeof import('@rookie-ui/element-plus')['Table']
    EaProgress: typeof import('@rookie-ui/element-plus')['Progress']

    // EaButton: typeof Components.Button,
    // EaChooseCity: typeof Components.ChooseCity
    // EaChooseTime: typeof Components.ChooseTime
    // EaChooseDate: typeof Components.ChooseDate
    // EaChooseIcon: typeof Components.ChooseIcon
    // EaIcon: typeof Components.Icon
    // EaTable: typeof Components.Table
    // EaProgress: typeof Components.Progress
    // AgelCheckbox: typeof import('./src/components/AgelCheckbox/AgelCheckbox.vue')['default']
    // AgelDynamicTags: typeof import('./src/components/AgelDynamicTags/AgelDynamicTags.vue')['default']
    // AgelFormDesc: typeof import('./src/components/AgelFormDesc/AgelFormDesc.vue')['default']
    // AgelFormGrid: typeof import('./src/components/AgelFormGrid/AgelFormGrid.vue')['default']
    // AgelFormItem: typeof import('./src/components/AgelFormItem/AgelFormItem.vue')['default']
    // AgelFormItems: typeof import('./src/components/AgelFormItems/AgelFormItems.vue')['default']
    // AgelFormTableditor: typeof import('./src/components/AgelFormTableditor/AgelFormTableditor.vue')['default']
    // AgelIcon: typeof import('./src/components/AgelIcon/AgelIcon.vue')['default']
    // AgelMenu: typeof import('./src/components/AgelMenu/AgelMenu.vue')['default']
    // AgelMenuItem: typeof import('./src/components/AgelMenu/AgelMenuItem.vue')['default']
    // AgelNavTabs: typeof import('./src/components/AgelNavTabs/AgelNavTabs.vue')['default']
    // AgelRadio: typeof import('./src/components/AgelRadio/AgelRadio.vue')['default']
    // AgelSelect: typeof import('./src/components/AgelSelect/AgelSelect.vue')['default']
    // AgelTable: typeof import('./src/components/AgelTable/AgelTable.vue')['default']
    // AgelUpload: typeof import('./src/components/AgelUpload/AgelUpload.vue')['default']
    Button: typeof import('./src/components/button/button.vue')['default']
    Icon: typeof import('./src/components/icon/icon.vue')['default']
  }
}


export {}